# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.

# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.
title: Công ty TNHH Năng Lượng Gió Xanh NTT
email: your-email@example.com
description: > # this means to ignore newlines until "baseurl:"
  Yet another Jekyll theme. It is designed for business purpose and ported by 
  Melvin Ch'ng.
baseurl: "" # the subpath of your site, e.g. /blog
url: "http://nangluonggioxanh.com" # the base hostname & protocol for your site, e.g. http://example.com

# Company Information
company_name: Công ty TNHH Năng Lượng Gió Xanh	NTT
address_line: Hà Nội, Việt Nam
telephone_number: 11111
fax_number: 11111
company_email: hello@LawOffice.org
google_map: https://www.google.com/maps/embed?pb=!1m18!1m12!1m3!1d3724.0469085942013!2d105.85015431478456!3d21.03080899308464!2m3!1f0!2f0!3f0!3m2!1i1024!2i768!4f13.1!3m3!1m2!1s0x0%3A0x0!2zMjHCsDAxJzUwLjkiTiAxMDXCsDUxJzA4LjQiRQ!5e0!3m2!1sen!2s!4v1565418225814!5m2!1sen!2s

# Social Link
facebook_link: http://www.facebook.com
googleplus_link: http://zalo.me

# Build settings
markdown: kramdown
plugins:
  - jekyll-feed

# Exclude from processing.
# The following items will not be processed, by default. Create a custom list
# to override the default setting.
# exclude:
#   - Gemfile
#   - Gemfile.lock
#   - node_modules
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/
